apiVersion: v1
kind: Service
metadata:
  name: expensy-service
  namespace: expensy
  labels:
    app: expensy
spec:
  type: ClusterIP
  selector:
    app: expensy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000