# sonarqube-db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db
  namespace: expensy
  labels:
    app: sonarqube-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-db
  template:
    metadata:
      labels:
        app: sonarqube-db
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: expensy-secret
                  key: SONAR_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expensy-secret
                  key: SONAR_DB_PASSWORD
            - name: POSTGRES_DB
              value: sonarqube
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: sonarqube-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: sonarqube-db-data
          emptyDir: {}

---
# sonarqube-db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-db
  namespace: expensy
  labels:
    app: sonarqube-db
spec:
  type: ClusterIP
  selector:
    app: sonarqube-db
  ports:
    - port: 5432
      targetPort: 5432